# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: get-version-reference-from-json-file

description: Get the Version Reference from the JSON file.

inputs:
  jq-filter:
    required: true    # [required]
    description: >
      The jq filter expression used to extract the desired version reference from the JSON file.
  json-file:
    required: true    # [required]
    description: >
      The path to the JSON file (typically references.json) from which to extract the version reference.
  working-directory:
    required: false
    default: ${{ github.workspace }}
    description: >
      The directory from which to run commands or locate files. Defaults to '\$\{\{ github.workspace \}\}'.

outputs:
  VERSION_REFERENCE:
    value: ${{ steps.gvi.outputs.VERSION_REFERENCE }}
    description: >
      The extracted version reference string based on the specified jq filter and input file.

runs:
  using: composite
  steps:
    # Refer to:
    # - https://github.com/peter-evans/create-pull-request/issues/2634#issuecomment-1870136711
    # - https://github.com/github/docs/issues/21529
    # - https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
    - name: Get the Version Reference from references.json
      id: gvi
      shell: bash
      run: |
        JQ_FILTER="${{ inputs.jq-filter }}"
        JSON_FILE=$(echo "${{ inputs.json-file }}" | sed 's#\\#/#g' | sed 's#^\([A-Za-z]\):#/\L\1#')
        WORKING_DIRECTORY=$(echo "${{ inputs.working-directory }}" | sed 's#\\#/#g' | sed 's#^\([A-Za-z]\):#/\L\1#')

        cd ${WORKING_DIRECTORY}

        VERSION_REFERENCE=$(jq "${JQ_FILTER}" "${JSON_FILE}")
        DELIMITER="$(openssl rand -hex 8)"
        echo "VERSION_REFERENCE<<${DELIMITER}"  >> ${GITHUB_OUTPUT}
        echo "${VERSION_REFERENCE}"             >> ${GITHUB_OUTPUT}
        echo "${DELIMITER}"                     >> ${GITHUB_OUTPUT}
        echo "VERSION_REFERENCE:"
        echo "${VERSION_REFERENCE}"
