# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE-BSD for details.

name: get-version-from-pull-request-title

description: Get the Version from the Pull Request Title.

inputs:
  pull-request-title:
    required: true    # [Required]
    description: >
      [Required] The title of the pull request, expected to contain a version in the format 'pot(<version>):'

outputs:
  VERSION:
    value: ${{ steps.gvprt.outputs.VERSION }}
    description: >
      The version string extracted from the pull request title, based on the format 'pot(<version>):'.

runs:
  using: composite
  steps:
    - name: Get VERSION from the Pull Request Title
      id: gvprt
      shell: bash
      run: |
        PULL_REQUEST_TITLE="${{ inputs.pull-request-title }}"
        VERSION_REGEX="pot\(([^)]+)\):"
        # See https://stackoverflow.com/a/218217/16265240 for details.
        if [[ ${PULL_REQUEST_TITLE} =~ ${VERSION_REGEX} ]]; then
          VERSION="${BASH_REMATCH[1]}"
          echo "Found version: ${VERSION}"
        else
          echo "Error: No version found in PR title." >&2
          exit 1
        fi
        echo "VERSION=${VERSION}" >> ${GITHUB_OUTPUT}
        echo "VERSION:"
        echo "${VERSION}"
