# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE-BSD for details.

name: install-cmake

description: Install CMake

inputs:
  cmake-version:
    required: false
    default: ''
    description: >
      The specific version of CMake to install. Defaults to an empty string.

runs:
  using: composite
  steps:
    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v2.0
      with:
        cmake-version: ${{ inputs.cmake-version }}
