# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: use-gettext-compendium

on:
  workflow_call:
    inputs:
      RUNNER:
        type: string
        required: true    # [Required]
        description: >
          [Required] The runner image for executing the job.
      CHECKOUT:
        type: string
        required: true    # [Required]
        description: >
          [Required] The git reference to be checked out.
      CMAKE_VERSION:
        type: string
        required: false
        default: ''
        description: >
          [Optional] The version of the CMake command. Defaults to an empty string.
      VERSION:
        type: string
        required: true    # [Required]
        description: >
          [Required] The version of the documentation.
      LANGUAGE:
        type: string
        required: true    # [Required]
        description: >
          [Required] The language of the documentation.
      ENABLE_JOB:
        type: string
        required: true    # [Required]
        description: >
          [Required] Whether to enable the job (`true` or `false`).
      ACTOR_NAME:
        type: string
        required: true    # [Required]
        description: >
          [Required] The user name of the GitHub actor.
      ACTOR_EMAIL:
        type: string
        required: true    # [Required]
        description: >
          [Required] The user email of the GitHub actor.
    secrets:
      ACTOR_GITHUB_TOKEN:
        required: true    # [Required]
        description: >
          [Required] The personal access token of the GitHub actor.

jobs:
  gettext-compend-po:
    if: ${{ inputs.ENABLE_JOB == 'true' }}
    runs-on: ${{ inputs.RUNNER }}
    steps:
      - name: Print Contexts/Inputs/Secrets
        shell: bash
        run: |
          echo "[Contexts]"
          echo "github.job = ${{ github.job }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.ref_name = ${{ github.ref_name }}"
          echo "github.event_name = ${{ github.event_name }}"
          echo "github.event.action = ${{ github.event.action }}"
          echo "github.event.number = ${{ github.event.number }}"
          echo "github.workflow = ${{ github.workflow }}"
          echo "github.workflow_ref = ${{ github.workflow_ref }}"
          echo "github.run_id = ${{ github.run_id }}"
          echo "github.run_number = ${{ github.run_number }}"
          echo "github.run_attempt = ${{ github.run_attempt }}"
          echo "github.server_url = ${{ github.server_url }}"
          echo "github.repository = ${{ github.repository }}"
          echo "github.workspace = ${{ github.workspace }}"
          echo "[Inputs]"
          echo "inputs.RUNNER = ${{ inputs.RUNNER }}"
          echo "inputs.CHECKOUT = ${{ inputs.CHECKOUT }}"
          echo "inputs.CMAKE_VERSION = ${{ inputs.CMAKE_VERSION }}"
          echo "inputs.VERSION = ${{ inputs.VERSION }}"
          echo "inputs.LANGUAGE = ${{ inputs.LANGUAGE }}"
          echo "inputs.ENABLE_JOB = ${{ inputs.ENABLE_JOB }}"
          echo "inputs.ACTOR_NAME = ${{ inputs.ACTOR_NAME }}"
          echo "inputs.ACTOR_EMAIL = ${{ inputs.ACTOR_EMAIL }}"
          echo "[Secrets]"
          echo "secrets.ACTOR_GITHUB_TOKEN = ${{ secrets.ACTOR_GITHUB_TOKEN }}"

      - name: Checkout to '${{ inputs.CHECKOUT }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.CHECKOUT }}
          token: ${{ secrets.ACTOR_GITHUB_TOKEN }}
          submodules: true
          fetch-depth: 0

      - name: Install CMake
        uses: ltdorgtest/ci-common/.github/actions/install-cmake@main
        with:
          cmake-version: ${{ inputs.CMAKE_VERSION }}

      - name: Install Gettext
        uses: ltdorgtest/ci-common/.github/actions/install-gettext@main

      - name: Get Other Caches from the versions.json file
        id: gocv
        uses: ltdorgtest/ci-common/.github/actions/get-other-caches-from-versions-file@main
        with:
          version: ${{ inputs.VERSION }}
          versions-file: 'versions.json'

      - name: Configure the '${{ inputs.LANGUAGE }}' preset for '${{ inputs.VERSION }}' version
        uses: ltdorgtest/ci-common/.github/actions/cmake-configure-preset@main
        with:
          config-preset: ${{ inputs.LANGUAGE }}
          cache-version: ${{ inputs.VERSION }}
          cache-version-compendium: ${{ steps.gocv.outputs.VERSION_COMPENDIUM }}
          cache-auto-depend: 'OFF'

      - name: Build the 'gettext_compendium' target
        uses: ltdorgtest/ci-common/.github/actions/cmake-build-target@main
        with:
          build-directory: out/build/${{ inputs.LANGUAGE }}
          build-target: 'gettext_compendium'

      - name: Get the Current Job's Context
        id: gcjc
        uses: qoomon/actions--context@v4
        with:
          token: ${{ secrets.ACTOR_GITHUB_TOKEN }}

      - name: Check Outputs of the Current Job's Context
        shell: bash
        run: |
          echo "Job Name:     ${{ steps.gcjc.outputs.job_name }}"
          echo "Job ID:       ${{ steps.gcjc.outputs.job_id }}"
          echo "Job URL:      ${{ steps.gcjc.outputs.job_url }}"
          echo "Run ID:       ${{ steps.gcjc.outputs.run_id }}"
          echo "Run Attempt:  ${{ steps.gcjc.outputs.run_attempt }}"
          echo "Run Number:   ${{ steps.gcjc.outputs.run_number }}"
          echo "Run URL:      ${{ steps.gcjc.outputs.run_url }}"

      - name: Set up mutex for 'l10n' branch
        uses: ben-z/gh-action-mutex@v1.0.0-alpha.9
        with:
          branch: 'mutex/l10n'
          repo-token: ${{ secrets.ACTOR_GITHUB_TOKEN }}

      - name: Add and Commit Changes
        id: acc
        uses: EndBug/add-and-commit@v9
        with:
          cwd: './l10n'
          add: './${{ inputs.VERSION }}'
          pull: '--rebase --autostash'  # required 'actions/checkout' with 'fetch-depth: 0'
          author_name: ${{ inputs.ACTOR_NAME }}
          author_email: ${{ inputs.ACTOR_EMAIL }}
          message: |
            🌐 tr(${{ inputs.VERSION }}): merge po with compendium of '${{ steps.gocv.outputs.VERSION_COMPENDIUM }}'

            merge .po files of '${{ inputs.VERSION }}' with compendium of '${{ steps.gocv.outputs.VERSION_COMPENDIUM }}'.

            created by the GitHub Actions:

            - file: ${{ github.server_url }}/${{ github.repository }}/actions/workflows/${{ github.workflow }}.yml
            - run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            - job: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ steps.gcjc.outputs.job_id }}

      - name: Check Outputs of the Commit
        if: ${{ steps.acc.outputs.committed == 'true' }}
        shell: bash
        run: |
          echo "Commit's SHA = ${{ steps.acc.outputs.commit_long_sha }}"
          echo "Commit's URL = ${{ github.server_url }}/${{ github.repository }}/commit/${{ steps.acc.outputs.commit_long_sha }}"
